name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      description: >
        You can see your macOS version by clicking the Apple Symbol at the top 
        left of your menubar and select `About This Mac`.
      placeholder: "e.g., macOS 13.4.1"
    validations:
      required: true
  - type: input
    id: device-model
    attributes:
      label: Device Model
      description: >
        You can see your device model by clicking the Apple Symbol at the top 
        left of your menubar and select `About This Mac`.
      placeholder: "e.g., iMac 24-inch, M1, 2021"
    validations:
      required: true
  - type: textarea
    id: debugging-log
    attributes:
      label: Debugging Log
      description: "You can get a debugging log by opening the workflow in Alfred preferences and pressing `⌘ + D`. A small window will open up which will log everything happening during the execution of the Workflow. Use the malfunctioning part of the workflow once more, copy the content of the log window, and paste it here. If the debugging log is long, please attach it as file instead of pasting everything in here."
      render: Text
    validations:
      required: true
  - type: textarea
    id: workflow-configuration
    attributes:
      label: Workflow Configuration
      description: "Please add a screenshot of all your [workflow configuration](https://www.alfredapp.com/help/workflows/user-configuration/)."
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have [updated to the latest version](https://github.com/chrisgrieser/alfred-atop/releases/latest) of this workflow.
          required: true
        - label: I am using Alfred 5. (Older versions are not supported anymore.)
          required: true
